Revert "pal: Move from exception handling to regular status check patterns."
This is reverted commit of Move from exception handling to regular
status check patterns.

Reason for revert: <compilation error: FAILED:
out/target/product/canoe/obj/DLKM/wcd937x_dlkm.ko_intermediates/wcd937x_dlkm.ko>

Signed-off-by: Chiluka Rohith <rchiluka@qti.qualcomm.com>